### PR TITLE
Move files to the .NET Core solution structure

### PR DESCRIPTION
**Pull request by piXel-m**
Upgrade solution and project to .NET Core 5.0
Upgrade code files to .NET Core 5.0
Implement Nominatim as geocoding provider
Implement GeoNames as geocoding provider
Update the readme.md

### CODE REVIEW

**Comment by chadly** [comment]
@piXel-m wow, thanks for this. There is a lot going on here. I appreciate the effort you put into this but it seems like it is going to be very hard to integrate. A couple of things that jump out immediately:

* It looks like you replaced tabs with spaces in every single source file. This makes it impossible for git to track the file renames and to merge back into `master` especially since it looks like this branch isn't based off the latest `master`.
* You added two new geocoding providers into this PR. It will be easier to review all of the changes if you keep the scope of the PR smaller.

I would love to integrate some of these changes into the project. If you want to help out, I have a branch called `netcore` where I've done some of the work of moving the solution structure to the new `xproj` project format. It builds against `net451` but but not against `netcore5`, though. It seems like you have `netcore5` working on your branch. If you want to checkout the `netcore` branch and port your changes to that branch and submit a PR with those changes, that would be very helpful.

As far as the two new geocoding providers, I would be happy to review those new features as separate PRs.

**Comment by piXel-m** [comment]
@chadly I'll try to 

- take the latest `master`
- reformat the code files with tabs
- seperate the providers from the upgrade to `netcore 5`

In case of the `dnxcore5` I would prever, that we should use a seperate branch for each framework version right now, cause there are a lot of diffrences in the .NET classes.
Later we should merge that by using `#if` conditions for `net451` and `netcore5`.

**Comment by piXel-m** [comment]
@chadly 
Right now I've restructured the project structure as your dnx upgrade and reformated the files.
For the providers I'll create new feature-branches with a seperate pull requests.

**Comment by chadly** [comment]
@piXel-m this is looking better. Could you open a new PR with your same `upgrade-to-dotnetcore` branch against the `net-core` branch in this repo? I don't think there is a way to update this PR to point to a new branch.

**Comment by piXel-m** [comment]
Was moved to PR#51

**Pull request closed without merging**
