### PR TITLE
Added place_id to GoogleAddress

### PR DESCRIPTION
**Pull request by jaxuk**
I need the place_id from Google Addresses to easily link data, so I've added it in - I'm sure it'll be useful to others too.

### CODE REVIEW

**Comment by chadly** [comment]
Thanks!

**Comment by jaxuk** [comment]
No problem. Any idea when a build including this will get released? I had
issues trying to build the source.

**Comment by vladimirlapacek** [comment]
I would also appreciate having access to place_id, so a new NuGet build would be great. I may be missing something, but the above change does not seem to include a public getter for the place_id field. How are you getting it in your code?

Thanks.

**Comment by chadly** [comment]
See #55

**Comment by vladimirlapacek** [comment]
OK, I see what happened. Can I help with sorting out the spacing problem? Would that speed up the change adoption in master and creating a new NuGet eventually?

**Comment by chadly** [comment]
sure, PRs are always welcome

**Pull request merged**
